---
info:
  app:
    name: formation
    description: Microservice FORMATION
    version: 1.0.0.0
message-properties-file: formation.message.properties
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        include: health,info,prometheus
    info:
      git:
        mode: full
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
      cache:
        time-to-live: 300s
    prometheus:
      enabled: true
      cache:
        time-to-live: 30s
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/formation?useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

---
spring:
  profiles:
    active: dev-local
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: false
  datasource:
    username: 
    password:
