info:
  app:
    name: formation 
    description: Microservice FORMATION
    version: 1.0.0.0
    
message-properties-file: formation.message.properties
    
# Spring Boot Actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        include: "health,info,prometheus"
    info:
      git:
        mode: full
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
      cache:
        time-to-live: 300s
    prometheus:
      enabled: true
      cache:
        time-to-live: 30s
        

  
spring:
 # data source mysql DB settings
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/formation
   username:
   password:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true 
    # Hibernate ddl strategy (create, create-drop, update)
    # Dialect database
   properties: 
     hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect

# config registry
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true

        
# profil DEV-LOCAL
---  
spring:
  profiles:
    active: dev-local
  # Show or not log sql
  jpa: 
   hibernate.ddl-auto: create
   generate-ddl: true 
   show-sql: false
  datasource:
   username: 
   password: